/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "gurskgtmcfiormucpvyk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1cnNrZ3RtY2Zpb3JtdWNwdnlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMjc1ODMsImV4cCI6MjA3NzgwMzU4M30.4nOJijQtGoZvISMesF79wDKL6YW39L0oI3j3ErD9Pp4"